[phases.setup]
nixPkgs = ['...', 'templ']

[phases.build]
cmds = ['templ generate', 'go build -o ./tmp/main .']

# TODO add tests
# [phases.test]
# cmds = ["yarn run test"]
# dependsOn = ["build"]

[start]
cmd = './tmp/main'